apiVersion: v1
kind: Pod
metadata:
  name: web
  labels: 
    app: mynginx
    
spec:
  containers: 
    - name: web-container
      image : nginx
      ports: 
        - containerPort: 80
