apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  labels:
    app: my-web

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: web-container
          image: nginx
          ports:
            - containerPort: 80
